# Encoding

In [1]:
import pandas as pd

In [25]:
df=pd.read_csv('/Users/sunnatabdurayimov/Downloads/Machine_Learning/encoding.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       1000 non-null   int64
 1   Quarter                    1000 non-null   str
 2   Product Model              995 non-null    str
 3   5G Capability              975 non-null    str
 4   Units Sold                 1000 non-null   int64
 5   Revenue ($)                1000 non-null   float64
 6   Market Share (%)           999 non-null    float64
 7   Regional 5G Coverage (%)   1000 non-null   float64
 8   5G Subscribers (millions)  1000 non-null   float64
 9   Avg 5G Speed (Mbps)        1000 non-null   float64
 10  Preference for 5G (%)      1000 non-null   float64
 11  Region                     996 non-null    str
 12  Color                      3 non-null      str
dtypes: float64(6), int64(2), str(5)
memory usage: 101.7 KB

In [15]:
df.head()

,Year,Quarter,Product Model,5G Capability,Units Sold,Revenue ($),Market Share (%),Regional 5G Coverage (%),5G Subscribers (millions),Avg 5G Speed (Mbps),Preference for 5G (%),Region
0,2019,Q1,Galaxy S10,No,26396,4.212951e+06,1.04,57.36,39.55,293.10,55.87,Asia-Pacific
1,2019,Q1,Galaxy Note10,No,25671,7.240266e+06,2.82,85.80,42.58,67.46,37.26,Latin America
2,2019,Q1,Galaxy S20,No,16573,2.560833e+07,-0.03,47.02,3.78,77.25,84.66,Middle East & Africa
3,2019,Q1,Galaxy Note20,No,7177,2.198442e+07,0.84,25.70,23.41,105.27,40.03,North America
4,2019,Q1,Galaxy S21,No,45633,1.634244e+07,2.36,89.13,44.43,206.17,76.88,Latin America

In [5]:
df.isnull().sum()

Year                           0
Quarter                        0
Product Model                  5
5G Capability                 25
Units Sold                     0
Revenue ($)                    0
Market Share (%)               1
Regional 5G Coverage (%)       0
5G Subscribers (millions)      0
Avg 5G Speed (Mbps)            0
Preference for 5G (%)          0
Region                         4
Color                        997
dtype: int64

#drop

In [10]:
#df.drop('Color',axis=1,inplace=True)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       1000 non-null   int64
 1   Quarter                    1000 non-null   str
 2   Product Model              995 non-null    str
 3   5G Capability              975 non-null    str
 4   Units Sold                 1000 non-null   int64
 5   Revenue ($)                1000 non-null   float64
 6   Market Share (%)           999 non-null    float64
 7   Regional 5G Coverage (%)   1000 non-null   float64
 8   5G Subscribers (millions)  1000 non-null   float64
 9   Avg 5G Speed (Mbps)        1000 non-null   float64
 10  Preference for 5G (%)      1000 non-null   float64
 11  Region                     996 non-null    str
 12  Color                      3 non-null      str
dtypes: float64(6), int64(2), str(5)
memory usage: 101.7 KB

In [ ]:
#df.dropna(inplace=True)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       3 non-null      int64
 1   Quarter                    3 non-null      str
 2   Product Model              3 non-null      str
 3   5G Capability              3 non-null      str
 4   Units Sold                 3 non-null      int64
 5   Revenue ($)                3 non-null      float64
 6   Market Share (%)           3 non-null      float64
 7   Regional 5G Coverage (%)   3 non-null      float64
 8   5G Subscribers (millions)  3 non-null      float64
 9   Avg 5G Speed (Mbps)        3 non-null      float64
 10  Preference for 5G (%)      3 non-null      float64
 11  Region                     3 non-null      str
 12  Color                      3 non-null      str
dtypes: float64(6), int64(2), str(5)
memory usage: 444.0 bytes

In [26]:
df.isnull().sum()

Year                           0
Quarter                        0
Product Model                  5
5G Capability                 25
Units Sold                     0
Revenue ($)                    0
Market Share (%)               1
Regional 5G Coverage (%)       0
5G Subscribers (millions)      0
Avg 5G Speed (Mbps)            0
Preference for 5G (%)          0
Region                         4
Color                        997
dtype: int64

In [40]:
df.fillna({'Region':df['Region'].mode()[0]},inplace=True)

,Year,Quarter,Product Model,5G Capability,Units Sold,Revenue ($),Market Share (%),Regional 5G Coverage (%),5G Subscribers (millions),Avg 5G Speed (Mbps),Preference for 5G (%),Region,Color
0,2019,Q1,Galaxy S10,No,26396,4.212951e+06,1.04,57.36,39.55,293.10,55.87,Asia-Pacific,Red
1,2019,Q1,Galaxy Note10,No,25671,7.240266e+06,2.82,85.80,42.58,67.46,37.26,Latin America,Green
2,2019,Q1,Galaxy S20,No,16573,2.560833e+07,-0.03,47.02,3.78,77.25,84.66,Middle East & Africa,Blue
3,2019,Q1,Galaxy Note20,No,7177,2.198442e+07,0.84,25.70,23.41,105.27,40.03,North America,NaN
4,2019,Q1,Galaxy S21,No,45633,1.634244e+07,2.36,89.13,44.43,206.17,76.88,Latin America,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,Q4,Galaxy S22 5G,Yes,36216,2.995937e+07,3.82,70.59,46.92,177.43,63.86,Latin America,NaN
996,2022,Q2,Galaxy S21,No,33806,2.369938e+07,-0.23,77.31,47.51,129.70,78.41,North America,NaN
997,2022,Q1,Galaxy S10,No,23678,2.330203e+07,0.58,45.61,43.79,156.56,72.06,Europe,NaN
998,2023,Q4,Galaxy Note10,No,35697,1.946256e+07,2.49,36.55,36.44,236.39,47.11,North America,NaN
999,2020,Q4,Galaxy Note20,No,7473,1.962177e+07,3.88,74.66,27.55,177.22,72.36,North America,NaN

In [39]:
df.fillna({'Market Share (%)':df['Market Share (%)'].mean()},inplace=True)

,Year,Quarter,Product Model,5G Capability,Units Sold,Revenue ($),Market Share (%),Regional 5G Coverage (%),5G Subscribers (millions),Avg 5G Speed (Mbps),Preference for 5G (%),Region,Color
0,2019,Q1,Galaxy S10,No,26396,4.212951e+06,1.04,57.36,39.55,293.10,55.87,Asia-Pacific,Red
1,2019,Q1,Galaxy Note10,No,25671,7.240266e+06,2.82,85.80,42.58,67.46,37.26,Latin America,Green
2,2019,Q1,Galaxy S20,No,16573,2.560833e+07,-0.03,47.02,3.78,77.25,84.66,Middle East & Africa,Blue
3,2019,Q1,Galaxy Note20,No,7177,2.198442e+07,0.84,25.70,23.41,105.27,40.03,North America,NaN
4,2019,Q1,Galaxy S21,No,45633,1.634244e+07,2.36,89.13,44.43,206.17,76.88,Latin America,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,Q4,Galaxy S22 5G,Yes,36216,2.995937e+07,3.82,70.59,46.92,177.43,63.86,Latin America,NaN
996,2022,Q2,Galaxy S21,No,33806,2.369938e+07,-0.23,77.31,47.51,129.70,78.41,North America,NaN
997,2022,Q1,Galaxy S10,No,23678,2.330203e+07,0.58,45.61,43.79,156.56,72.06,Europe,NaN
998,2023,Q4,Galaxy Note10,No,35697,1.946256e+07,2.49,36.55,36.44,236.39,47.11,North America,NaN
999,2020,Q4,Galaxy Note20,No,7473,1.962177e+07,3.88,74.66,27.55,177.22,72.36,North America,NaN

In [41]:
df.fillna({'5G Capability':'No'},inplace=True)

,Year,Quarter,Product Model,5G Capability,Units Sold,Revenue ($),Market Share (%),Regional 5G Coverage (%),5G Subscribers (millions),Avg 5G Speed (Mbps),Preference for 5G (%),Region,Color
0,2019,Q1,Galaxy S10,No,26396,4.212951e+06,1.04,57.36,39.55,293.10,55.87,Asia-Pacific,Red
1,2019,Q1,Galaxy Note10,No,25671,7.240266e+06,2.82,85.80,42.58,67.46,37.26,Latin America,Green
2,2019,Q1,Galaxy S20,No,16573,2.560833e+07,-0.03,47.02,3.78,77.25,84.66,Middle East & Africa,Blue
3,2019,Q1,Galaxy Note20,No,7177,2.198442e+07,0.84,25.70,23.41,105.27,40.03,North America,NaN
4,2019,Q1,Galaxy S21,No,45633,1.634244e+07,2.36,89.13,44.43,206.17,76.88,Latin America,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,Q4,Galaxy S22 5G,Yes,36216,2.995937e+07,3.82,70.59,46.92,177.43,63.86,Latin America,NaN
996,2022,Q2,Galaxy S21,No,33806,2.369938e+07,-0.23,77.31,47.51,129.70,78.41,North America,NaN
997,2022,Q1,Galaxy S10,No,23678,2.330203e+07,0.58,45.61,43.79,156.56,72.06,Europe,NaN
998,2023,Q4,Galaxy Note10,No,35697,1.946256e+07,2.49,36.55,36.44,236.39,47.11,North America,NaN
999,2020,Q4,Galaxy Note20,No,7473,1.962177e+07,3.88,74.66,27.55,177.22,72.36,North America,NaN

In [42]:
df.isnull().sum()

Year                           0
Quarter                        0
Product Model                  5
5G Capability                  0
Units Sold                     0
Revenue ($)                    0
Market Share (%)               0
Regional 5G Coverage (%)       0
5G Subscribers (millions)      0
Avg 5G Speed (Mbps)            0
Preference for 5G (%)          0
Region                         0
Color                        997
dtype: int64

In [43]:
df.fillna({'Product Model':df['Product Model'].mode()[0]},inplace=True)

,Year,Quarter,Product Model,5G Capability,Units Sold,Revenue ($),Market Share (%),Regional 5G Coverage (%),5G Subscribers (millions),Avg 5G Speed (Mbps),Preference for 5G (%),Region,Color
0,2019,Q1,Galaxy S10,No,26396,4.212951e+06,1.04,57.36,39.55,293.10,55.87,Asia-Pacific,Red
1,2019,Q1,Galaxy Note10,No,25671,7.240266e+06,2.82,85.80,42.58,67.46,37.26,Latin America,Green
2,2019,Q1,Galaxy S20,No,16573,2.560833e+07,-0.03,47.02,3.78,77.25,84.66,Middle East & Africa,Blue
3,2019,Q1,Galaxy Note20,No,7177,2.198442e+07,0.84,25.70,23.41,105.27,40.03,North America,NaN
4,2019,Q1,Galaxy S21,No,45633,1.634244e+07,2.36,89.13,44.43,206.17,76.88,Latin America,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,Q4,Galaxy S22 5G,Yes,36216,2.995937e+07,3.82,70.59,46.92,177.43,63.86,Latin America,NaN
996,2022,Q2,Galaxy S21,No,33806,2.369938e+07,-0.23,77.31,47.51,129.70,78.41,North America,NaN
997,2022,Q1,Galaxy S10,No,23678,2.330203e+07,0.58,45.61,43.79,156.56,72.06,Europe,NaN
998,2023,Q4,Galaxy Note10,No,35697,1.946256e+07,2.49,36.55,36.44,236.39,47.11,North America,NaN
999,2020,Q4,Galaxy Note20,No,7473,1.962177e+07,3.88,74.66,27.55,177.22,72.36,North America,NaN

In [44]:
df.isnull().sum()

Year                           0
Quarter                        0
Product Model                  0
5G Capability                  0
Units Sold                     0
Revenue ($)                    0
Market Share (%)               0
Regional 5G Coverage (%)       0
5G Subscribers (millions)      0
Avg 5G Speed (Mbps)            0
Preference for 5G (%)          0
Region                         0
Color                        997
dtype: int64

In [46]:
df.fillna({'Color':df['Color'].mode()[0]},inplace=True)

,Year,Quarter,Product Model,5G Capability,Units Sold,Revenue ($),Market Share (%),Regional 5G Coverage (%),5G Subscribers (millions),Avg 5G Speed (Mbps),Preference for 5G (%),Region,Color
0,2019,Q1,Galaxy S10,No,26396,4.212951e+06,1.04,57.36,39.55,293.10,55.87,Asia-Pacific,Red
1,2019,Q1,Galaxy Note10,No,25671,7.240266e+06,2.82,85.80,42.58,67.46,37.26,Latin America,Green
2,2019,Q1,Galaxy S20,No,16573,2.560833e+07,-0.03,47.02,3.78,77.25,84.66,Middle East & Africa,Blue
3,2019,Q1,Galaxy Note20,No,7177,2.198442e+07,0.84,25.70,23.41,105.27,40.03,North America,Blue
4,2019,Q1,Galaxy S21,No,45633,1.634244e+07,2.36,89.13,44.43,206.17,76.88,Latin America,Blue
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,Q4,Galaxy S22 5G,Yes,36216,2.995937e+07,3.82,70.59,46.92,177.43,63.86,Latin America,Blue
996,2022,Q2,Galaxy S21,No,33806,2.369938e+07,-0.23,77.31,47.51,129.70,78.41,North America,Blue
997,2022,Q1,Galaxy S10,No,23678,2.330203e+07,0.58,45.61,43.79,156.56,72.06,Europe,Blue
998,2023,Q4,Galaxy Note10,No,35697,1.946256e+07,2.49,36.55,36.44,236.39,47.11,North America,Blue
999,2020,Q4,Galaxy Note20,No,7473,1.962177e+07,3.88,74.66,27.55,177.22,72.36,North America,Blue

In [48]:
df.nunique()

Year                           6
Quarter                        4
Product Model                 15
5G Capability                  2
Units Sold                   354
Revenue ($)                  360
Market Share (%)             275
Regional 5G Coverage (%)     344
5G Subscribers (millions)    350
Avg 5G Speed (Mbps)          358
Preference for 5G (%)        347
Region                         5
Color                          3
dtype: int64

# One-Hot

In [52]:
dummies=pd.get_dummies(df['Color'],prefix='ustun',dtype=int)

In [53]:
dummies

     ustun_Blue  ustun_Green  ustun_Red
0             0            0          1
1             0            1          0
2             1            0          0
3             1            0          0
4             1            0          0
..          ...          ...        ...
995           1            0          0
996           1            0          0
997           1            0          0
998           1            0          0
999           1            0          0

[1000 rows x 3 columns]

In [54]:
df=pd.concat([df.drop(columns=['Color']),dummies],axis=1)

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       1000 non-null   int64
 1   Quarter                    1000 non-null   str
 2   Product Model              1000 non-null   str
 3   5G Capability              1000 non-null   str
 4   Units Sold                 1000 non-null   int64
 5   Revenue ($)                1000 non-null   float64
 6   Market Share (%)           1000 non-null   float64
 7   Regional 5G Coverage (%)   1000 non-null   float64
 8   5G Subscribers (millions)  1000 non-null   float64
 9   Avg 5G Speed (Mbps)        1000 non-null   float64
 10  Preference for 5G (%)      1000 non-null   float64
 11  Region                     1000 non-null   str
 12  ustun_Blue                 1000 non-null   int64
 13  ustun_Green                1000 non-null   int64
 14  ustun_Red                  1000 non-null   int64
dtypes: float64(6), int64(5), str(4)
memory usage: 117.3 KB

In [57]:
df.head()

,Year,Quarter,Product Model,5G Capability,Units Sold,Revenue ($),Market Share (%),Regional 5G Coverage (%),5G Subscribers (millions),Avg 5G Speed (Mbps),Preference for 5G (%),Region,ustun_Blue,ustun_Green,ustun_Red
0,2019,Q1,Galaxy S10,No,26396,4.212951e+06,1.04,57.36,39.55,293.10,55.87,Asia-Pacific,0,0,1
1,2019,Q1,Galaxy Note10,No,25671,7.240266e+06,2.82,85.80,42.58,67.46,37.26,Latin America,0,1,0
2,2019,Q1,Galaxy S20,No,16573,2.560833e+07,-0.03,47.02,3.78,77.25,84.66,Middle East & Africa,1,0,0
3,2019,Q1,Galaxy Note20,No,7177,2.198442e+07,0.84,25.70,23.41,105.27,40.03,North America,1,0,0
4,2019,Q1,Galaxy S21,No,45633,1.634244e+07,2.36,89.13,44.43,206.17,76.88,Latin America,1,0,0

In [62]:
from sklearn.preprocessing import LabelEncoder

In [63]:
encoder=LabelEncoder()

In [64]:
encoder

LabelEncoder()

In [65]:
df['Region']=encoder.fit_transform(df['Region'])

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       1000 non-null   int64
 1   Quarter                    1000 non-null   str
 2   Product Model              1000 non-null   str
 3   5G Capability              1000 non-null   str
 4   Units Sold                 1000 non-null   int64
 5   Revenue ($)                1000 non-null   float64
 6   Market Share (%)           1000 non-null   float64
 7   Regional 5G Coverage (%)   1000 non-null   float64
 8   5G Subscribers (millions)  1000 non-null   float64
 9   Avg 5G Speed (Mbps)        1000 non-null   float64
 10  Preference for 5G (%)      1000 non-null   float64
 11  Region                     1000 non-null   int64
 12  ustun_Blue                 1000 non-null   int64
 13  ustun_Green                1000 non-null   int64
 14  ustun_Red                  1000 non-null   int64
dtypes: float64(6), int64(6), str(3)
memory usage: 117.3 KB

In [67]:
df['Quarter']=encoder.fit_transform(df['Quarter'])

In [69]:
df['5G Capability']=encoder.fit_transform(df['5G Capability'])

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       1000 non-null   int64
 1   Quarter                    1000 non-null   int64
 2   Product Model              1000 non-null   str
 3   5G Capability              1000 non-null   int64
 4   Units Sold                 1000 non-null   int64
 5   Revenue ($)                1000 non-null   float64
 6   Market Share (%)           1000 non-null   float64
 7   Regional 5G Coverage (%)   1000 non-null   float64
 8   5G Subscribers (millions)  1000 non-null   float64
 9   Avg 5G Speed (Mbps)        1000 non-null   float64
 10  Preference for 5G (%)      1000 non-null   float64
 11  Region                     1000 non-null   int64
 12  ustun_Blue                 1000 non-null   int64
 13  ustun_Green                1000 non-null   int64
 14  ustun_Red                  1000 non-null   int64
dtypes: float64(6), int64(8), str(1)
memory usage: 117.3 KB

In [71]:
df.head()

,Year,Quarter,Product Model,5G Capability,Units Sold,Revenue ($),Market Share (%),Regional 5G Coverage (%),5G Subscribers (millions),Avg 5G Speed (Mbps),Preference for 5G (%),Region,ustun_Blue,ustun_Green,ustun_Red
0,2019,0,Galaxy S10,0,26396,4.212951e+06,1.04,57.36,39.55,293.10,55.87,0,0,0,1
1,2019,0,Galaxy Note10,0,25671,7.240266e+06,2.82,85.80,42.58,67.46,37.26,2,0,1,0
2,2019,0,Galaxy S20,0,16573,2.560833e+07,-0.03,47.02,3.78,77.25,84.66,3,1,0,0
3,2019,0,Galaxy Note20,0,7177,2.198442e+07,0.84,25.70,23.41,105.27,40.03,4,1,0,0
4,2019,0,Galaxy S21,0,45633,1.634244e+07,2.36,89.13,44.43,206.17,76.88,2,1,0,0