# Imtihon

In [333]:
import pandas as pd

In [334]:
df=pd.read_csv('/Users/sunnatabdurayimov/Desktop/autosnm.csv')

# Data bilan tanishuv

In [335]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                371528 non-null  int64
 1   dateCrawled          371528 non-null  str
 2   name                 371528 non-null  str
 3   seller               371528 non-null  str
 4   offerType            371528 non-null  str
 5   price                371528 non-null  int64
 6   abtest               371528 non-null  str
 7   vehicleType          333659 non-null  str
 8   yearOfRegistration   371528 non-null  int64
 9   gearbox              351319 non-null  str
 10  powerPS              371528 non-null  int64
 11  model                351044 non-null  str
 12  kilometer            371528 non-null  int64
 13  monthOfRegistration  371528 non-null  int64
 14  fuelType             338142 non-null  str
 15  brand                371528 non-null  str
 16  notRepairedDamage    299468 non-null  str
 17  dateCreated          371528 non-null  str
 18  nrOfPictures         371528 non-null  int64
 19  postalCode           371528 non-null  int64
 20  lastSeen             371528 non-null  str
dtypes: int64(8), str(13)
memory usage: 59.5 MB

In [336]:
df.head()

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,...,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,...,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,...,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,...,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,...,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21

In [337]:
df.isnull().sum()

index                      0
dateCrawled                0
name                       0
seller                     0
offerType                  0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
dateCreated                0
nrOfPictures               0
postalCode                 0
lastSeen                   0
dtype: int64

In [338]:
df.columns

Index(['index', 'dateCrawled', 'name', 'seller', 'offerType', 'price',
       'abtest', 'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS',
       'model', 'kilometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='str')

# Data preprocessing

In [339]:
df.drop(['nrOfPictures','offerType'],axis=1,inplace=True)

In [340]:
for col in df.columns:
    if df[col].dtype=='object':
        df[col].fillna(df[col].mode()[0],inplace=True)

In [341]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                371528 non-null  int64
 1   dateCrawled          371528 non-null  str
 2   name                 371528 non-null  str
 3   seller               371528 non-null  str
 4   price                371528 non-null  int64
 5   abtest               371528 non-null  str
 6   vehicleType          333659 non-null  str
 7   yearOfRegistration   371528 non-null  int64
 8   gearbox              351319 non-null  str
 9   powerPS              371528 non-null  int64
 10  model                351044 non-null  str
 11  kilometer            371528 non-null  int64
 12  monthOfRegistration  371528 non-null  int64
 13  fuelType             338142 non-null  str
 14  brand                371528 non-null  str
 15  notRepairedDamage    299468 non-null  str
 16  dateCreated          371528 non-null  str
 17  postalCode           371528 non-null  int64
 18  lastSeen             371528 non-null  str
dtypes: int64(7), str(12)
memory usage: 53.9 MB

In [342]:
df.isnull().sum()

index                      0
dateCrawled                0
name                       0
seller                     0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
dateCreated                0
postalCode                 0
lastSeen                   0
dtype: int64

In [343]:
df.nunique()

index                  371528
dateCrawled            280500
name                   233531
seller                      2
price                    5597
abtest                      2
vehicleType                 8
yearOfRegistration        155
gearbox                     2
powerPS                   794
model                     251
kilometer                  13
monthOfRegistration        13
fuelType                    7
brand                      40
notRepairedDamage           2
dateCreated               114
postalCode               8150
lastSeen               182806
dtype: int64

# encoding

In [344]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [345]:
encoder=LabelEncoder()

In [346]:
encoder

LabelEncoder()

In [347]:
for col in df.columns:
    if df[col].dtype=='str':
        if df[col].nunique()<=2:
            dummies=pd.get_dummies(df[col],prefix='col',dtype=int)
            df=pd.concat([df.drop(columns=col),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [348]:
df.head()

,index,dateCrawled,name,price,vehicleType,yearOfRegistration,powerPS,model,kilometer,monthOfRegistration,...,postalCode,lastSeen,col_gewerblich,col_privat,col_control,col_test,col_automatik,col_manuell,col_ja,col_nein
0,0,164563,79207,480,8,1993,0,118,150000,0,...,70435,178839,0,1,0,1,0,1,0,0
1,1,164294,4112,18300,3,2011,190,251,125000,5,...,66954,178355,0,1,0,1,0,1,1,0
2,2,76564,90564,9800,7,2004,163,119,125000,8,...,90480,162956,0,1,0,1,1,0,0,0
3,3,106204,76592,1500,4,2001,75,118,150000,6,...,91074,45272,0,1,0,1,0,1,0,1
4,4,231164,170493,3600,4,2008,69,103,90000,7,...,60437,171913,0,1,0,1,0,1,0,1

In [349]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 23 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                371528 non-null  int64
 1   dateCrawled          371528 non-null  int64
 2   name                 371528 non-null  int64
 3   price                371528 non-null  int64
 4   vehicleType          371528 non-null  int64
 5   yearOfRegistration   371528 non-null  int64
 6   powerPS              371528 non-null  int64
 7   model                371528 non-null  int64
 8   kilometer            371528 non-null  int64
 9   monthOfRegistration  371528 non-null  int64
 10  fuelType             371528 non-null  int64
 11  brand                371528 non-null  int64
 12  dateCreated          371528 non-null  int64
 13  postalCode           371528 non-null  int64
 14  lastSeen             371528 non-null  int64
 15  col_gewerblich       371528 non-null  int64
 16  col_privat           371528 non-null  int64
 17  col_control          371528 non-null  int64
 18  col_test             371528 non-null  int64
 19  col_automatik        371528 non-null  int64
 20  col_manuell          371528 non-null  int64
 21  col_ja               371528 non-null  int64
 22  col_nein             371528 non-null  int64
dtypes: int64(23)
memory usage: 65.2 MB

# scaling

In [350]:
from sklearn.preprocessing import MinMaxScaler

In [351]:
scaler=MinMaxScaler()

In [352]:
scaler

MinMaxScaler()

In [353]:
num_col=df.select_dtypes(include=['int64',]).columns.drop('price')

In [354]:
num_col

Index(['index', 'dateCrawled', 'name', 'vehicleType', 'yearOfRegistration',
       'powerPS', 'model', 'kilometer', 'monthOfRegistration', 'fuelType',
       'brand', 'dateCreated', 'postalCode', 'lastSeen', 'col_gewerblich',
       'col_privat', 'col_control', 'col_test', 'col_automatik', 'col_manuell',
       'col_ja', 'col_nein'],
      dtype='str')

In [355]:
df[num_col]=scaler.fit_transform(df[num_col])

In [356]:
df.head()

,index,dateCrawled,name,price,vehicleType,yearOfRegistration,powerPS,model,kilometer,monthOfRegistration,...,postalCode,lastSeen,col_gewerblich,col_privat,col_control,col_test,col_automatik,col_manuell,col_ja,col_nein
0,0.000000,0.586679,0.339173,480,1.000,0.110346,0.00000,0.470120,1.000000,0.000000,...,0.701176,0.978305,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
1,0.000003,0.585720,0.017608,18300,0.375,0.112346,0.00950,1.000000,0.827586,0.416667,...,0.665989,0.975657,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.000005,0.272956,0.387805,9800,0.875,0.111568,0.00815,0.474104,0.827586,0.666667,...,0.903792,0.891420,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
3,0.000008,0.378625,0.327975,1500,0.500,0.111235,0.00375,0.470120,1.000000,0.500000,...,0.909796,0.247652,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
4,0.000011,0.824117,0.730069,3600,0.500,0.112012,0.00345,0.410359,0.586207,0.583333,...,0.600115,0.940417,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0

In [357]:
from sklearn.linear_model import LinearRegression

In [358]:
lr=LinearRegression()

In [359]:
lr

LinearRegression()

In [360]:
x=df.drop('price',axis=1)

In [361]:
x

,index,dateCrawled,name,vehicleType,yearOfRegistration,powerPS,model,kilometer,monthOfRegistration,fuelType,...,postalCode,lastSeen,col_gewerblich,col_privat,col_control,col_test,col_automatik,col_manuell,col_ja,col_nein
0,0.000000,0.586679,0.339173,1.000,0.110346,0.00000,0.470120,1.000000,0.000000,0.142857,...,0.701176,0.978305,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
1,0.000003,0.585720,0.017608,0.375,0.112346,0.00950,1.000000,0.827586,0.416667,0.428571,...,0.665989,0.975657,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.000005,0.272956,0.387805,0.875,0.111568,0.00815,0.474104,0.827586,0.666667,0.428571,...,0.903792,0.891420,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
3,0.000008,0.378625,0.327975,0.500,0.111235,0.00375,0.470120,1.000000,0.500000,0.142857,...,0.909796,0.247652,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
4,0.000011,0.824117,0.730069,0.500,0.112012,0.00345,0.410359,0.586207,0.583333,0.428571,...,0.600115,0.940417,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,0.999989,0.283851,0.762133,1.000,0.111679,0.00000,1.000000,0.103448,0.083333,1.000000,...,0.389251,0.922229,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
371524,0.999992,0.018242,0.751882,0.250,0.111123,0.00505,0.430279,0.827586,0.250000,0.142857,...,0.253389,0.089303,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
371525,0.999995,0.434551,0.917728,0.125,0.110679,0.00510,0.896414,1.000000,0.250000,0.428571,...,0.873053,0.985110,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
371526,0.999997,0.470330,0.820888,0.625,0.111346,0.00500,0.470120,1.000000,0.500000,0.428571,...,0.401259,0.450097,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
371527,1.000000,0.066143,0.169254,0.750,0.112568,0.01600,0.589641,0.310345,0.666667,0.142857,...,0.730398,0.372484,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0

In [362]:
y=df['price']

In [363]:
y

0           480
1         18300
2          9800
3          1500
4          3600
          ...
371523     2200
371524     1199
371525     9200
371526     3400
371527    28990
Name: price, Length: 371528, dtype: int64

# Train

In [364]:
from sklearn.model_selection import train_test_split

In [365]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [366]:
lr.fit(x_train,y_train)

LinearRegression()

In [367]:
x_train.shape

(297222, 22)

In [368]:
x_test.shape

(74306, 22)

In [369]:
y_train.shape

(297222,)

In [370]:
y_test.shape

(74306,)

# prediction

In [371]:
y_pred=lr.predict(x_test)

In [372]:
y_pred

array([-37328.12989267,  -9646.25989776,  12910.48444263, ...,
        15086.29037142,   9270.74056429,  46646.73475511], shape=(74306,))

# Evaluation

In [373]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [374]:
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [375]:
mae

38977.374511550544

In [376]:
mse

420361265377.97424

In [377]:
r2

-0.005401371817065792