# Algorithms

In [4]:
import pandas as pd

In [19]:
df=pd.read_csv('/Users/sunnatabdurayimov/Downloads/Bank_Personal_Loan_Modelling(1).csv')

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB

# encoding

In [21]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [22]:
encoder

LabelEncoder()

In [23]:
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
rac=RandomForestClassifier()

In [24]:
rac

RandomForestClassifier()

In [25]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

# scaling

In [26]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [27]:
scaler

MinMaxScaler()

In [28]:
for col in df.columns:
    df[col]=scaler.fit_transform(df[[col]])

In [29]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,0.0000,0.045455,0.086957,0.189815,0.936527,1.000000,0.16,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0002,0.500000,0.478261,0.120370,0.924872,0.666667,0.15,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0004,0.363636,0.391304,0.013889,0.977892,0.000000,0.10,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0006,0.272727,0.260870,0.425926,0.970931,0.000000,0.27,0.5,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0008,0.272727,0.239130,0.171296,0.939080,1.000000,0.10,0.5,0.0,0.0,0.0,0.0,0.0,1.0

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   float64
 1   Age                 5000 non-null   float64
 2   Experience          5000 non-null   float64
 3   Income              5000 non-null   float64
 4   ZIP Code            5000 non-null   float64
 5   Family              5000 non-null   float64
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   float64
 8   Mortgage            5000 non-null   float64
 9   Personal Loan       5000 non-null   float64
 10  Securities Account  5000 non-null   float64
 11  CD Account          5000 non-null   float64
 12  Online              5000 non-null   float64
 13  CreditCard          5000 non-null   float64
dtypes: float64(14)
memory usage: 547.0 KB

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
log_reg=LogisticRegression()

In [41]:
log_reg

LogisticRegression()

In [42]:
x---inputlar
y---output

NameError: name 'x' is not defined

In [43]:
num_col=df.select_dtypes(include=['float64']).columns

In [44]:
num_col

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg',
       'Education', 'Mortgage', 'Personal Loan', 'Securities Account',
       'CD Account', 'Online', 'CreditCard'],
      dtype='str')

In [45]:
x=df.drop('Personal Loan',axis=1)

In [46]:
x

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Securities Account,CD Account,Online,CreditCard
0,0.0000,0.045455,0.086957,0.189815,0.936527,1.000000,0.16,0.0,0.000000,1.0,0.0,0.0,0.0
1,0.0002,0.500000,0.478261,0.120370,0.924872,0.666667,0.15,0.0,0.000000,1.0,0.0,0.0,0.0
2,0.0004,0.363636,0.391304,0.013889,0.977892,0.000000,0.10,0.0,0.000000,0.0,0.0,0.0,0.0
3,0.0006,0.272727,0.260870,0.425926,0.970931,0.000000,0.27,0.5,0.000000,0.0,0.0,0.0,0.0
4,0.0008,0.272727,0.239130,0.171296,0.939080,1.000000,0.10,0.5,0.000000,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0.9992,0.136364,0.130435,0.148148,0.954731,0.000000,0.19,1.0,0.000000,0.0,0.0,1.0,0.0
4996,0.9994,0.159091,0.152174,0.032407,0.947174,1.000000,0.04,0.0,0.133858,0.0,0.0,1.0,0.0
4997,0.9996,0.909091,0.913043,0.074074,0.958463,0.333333,0.03,1.0,0.000000,0.0,0.0,0.0,0.0
4998,0.9998,0.954545,0.934783,0.189815,0.924242,0.666667,0.05,0.5,0.000000,0.0,0.0,1.0,0.0
4999,1.0000,0.113636,0.152174,0.347222,0.953758,0.666667,0.08,0.0,0.000000,0.0,0.0,1.0,1.0

In [47]:
y=df['Personal Loan'].astype(int)

In [48]:
y

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    0
4997    0
4998    0
4999    0
Name: Personal Loan, Length: 5000, dtype: int64

# spliting

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [51]:
x_train.shape

(4000, 13)

In [52]:
x_test.shape

(1000, 13)

In [53]:
y_train.shape

(4000,)

In [54]:
y_test.shape

(1000,)

# train

In [55]:
log_reg.fit(x_train,y_train)

LogisticRegression()

# predicting

In [56]:
y_pred=log_reg.predict(x_test)

In [57]:
y_pred[1:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

# Evaluation

In [58]:
from sklearn.metrics import accuracy_score

In [59]:
score=accuracy_score(y_test,y_pred)

In [60]:
print('Modelning aniqlik darajasi:',score)

Modelning aniqlik darajasi: 0.954