# Algorithm

In [5]:
import pandas as pd

In [6]:
df=pd.read_csv('Library/Mobile Documents/com~apple~Numbers/Documents/datasetpredict.csv')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 35 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   Daytime/evening attendance                      4417 non-null   float64
 5   Previous qualification                          4424 non-null   int64
 6   Nacionality                                     4424 non-null   int64
 7   Mother's qualification                          4424 non-null   int64
 8   Father's qualification                          4424 non-null   int64
 9   Mother's occupation                             4424 non-null   int64
 10  Father's occupation                             4424 non-null   int64
 11  Displaced                                       4424 non-null   int64
 12  Educational special needs                       4417 non-null   float64
 13  Debtor                                          4417 non-null   float64
 14  Tuition fees up to date                         4417 non-null   float64
 15  Gender                                          4417 non-null   float64
 16  Scholarship holder                              4417 non-null   float64
 17  Age at enrollment                               4424 non-null   int64
 18  International                                   4424 non-null   int64
 19  Curricular units 1st sem (credited)             4424 non-null   int64
 20  Curricular units 1st sem (enrolled)             4424 non-null   int64
 21  Curricular units 1st sem (evaluations)          4424 non-null   int64
 22  Curricular units 1st sem (approved)             4424 non-null   int64
 23  Curricular units 1st sem (grade)                4424 non-null   float64
 24  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 25  Curricular units 2nd sem (credited)             4424 non-null   int64
 26  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 27  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 28  Curricular units 2nd sem (approved)             4424 non-null   int64
 29  Curricular units 2nd sem (grade)                4424 non-null   float64
 30  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 31  Unemployment rate                               4424 non-null   float64
 32  Inflation rate                                  4424 non-null   float64
 33  GDP                                             4424 non-null   float64
 34  Target                                          4424 non-null   str
dtypes: float64(11), int64(23), str(1)
memory usage: 1.2 MB

In [8]:
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Nacionality,Mother's qualification,Father's qualification,Mother's occupation,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,8,5,2,1.0,1,1,13,10,6,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,6,1,11,1.0,1,1,1,3,4,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,5,1.0,1,1,22,27,10,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,8,2,15,1.0,1,1,23,27,6,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,12,1,3,0.0,1,1,22,28,10,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [9]:
df.isnull().sum()

Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance                        7
Previous qualification                            0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Displaced                                         0
Educational special needs                         7
Debtor                                            7
Tuition fees up to date                           7
Gender                                            7
Scholarship holder                                7
Age at enrollment                                 0
International                                     0
Curricular units 1st sem (credited)               0
Curricular units 1st sem (enrolled)               0
Curricular units 1st sem (evaluations)            0
Curricular units 1st sem (approved)               0
Curricular units 1st sem (grade)                  0
Curricular units 1st sem (without evaluations)    0
Curricular units 2nd sem (credited)               0
Curricular units 2nd sem (enrolled)               0
Curricular units 2nd sem (evaluations)            0
Curricular units 2nd sem (approved)               0
Curricular units 2nd sem (grade)                  0
Curricular units 2nd sem (without evaluations)    0
Unemployment rate                                 0
Inflation rate                                    0
GDP                                               0
Target                                            0
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
df.columns

Index(['Marital status', 'Application mode', 'Application order', 'Course',
       'Daytime/evening attendance', 'Previous qualification', 'Nacionality',
       'Mother's qualification', 'Father's qualification',
       'Mother's occupation', 'Father's occupation', 'Displaced',
       'Educational special needs', 'Debtor', 'Tuition fees up to date',
       'Gender', 'Scholarship holder', 'Age at enrollment', 'International',
       'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (enrolled)',
       'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (approved)',
       'Curricular units 1st sem (grade)',
       'Curricular units 1st sem (without evaluations)',
       'Curricular units 2nd sem (credited)',
       'Curricular units 2nd sem (enrolled)',
       'Curricular units 2nd sem (evaluations)',
       'Curricular units 2nd sem (approved)',
       'Curricular units 2nd sem (grade)',
       'Curricular units 2nd sem (without evaluations)', 'Unemployment rate',
       'Inflation rate', 'GDP', 'Target'],
      dtype='str')

In [12]:
df.drop('Nacionality',axis=1,inplace=True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 4413 entries, 0 to 4423
Data columns (total 34 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4413 non-null   int64
 1   Application mode                                4413 non-null   int64
 2   Application order                               4413 non-null   int64
 3   Course                                          4413 non-null   int64
 4   Daytime/evening attendance                      4413 non-null   float64
 5   Previous qualification                          4413 non-null   int64
 6   Mother's qualification                          4413 non-null   int64
 7   Father's qualification                          4413 non-null   int64
 8   Mother's occupation                             4413 non-null   int64
 9   Father's occupation                             4413 non-null   int64
 10  Displaced                                       4413 non-null   int64
 11  Educational special needs                       4413 non-null   float64
 12  Debtor                                          4413 non-null   float64
 13  Tuition fees up to date                         4413 non-null   float64
 14  Gender                                          4413 non-null   float64
 15  Scholarship holder                              4413 non-null   float64
 16  Age at enrollment                               4413 non-null   int64
 17  International                                   4413 non-null   int64
 18  Curricular units 1st sem (credited)             4413 non-null   int64
 19  Curricular units 1st sem (enrolled)             4413 non-null   int64
 20  Curricular units 1st sem (evaluations)          4413 non-null   int64
 21  Curricular units 1st sem (approved)             4413 non-null   int64
 22  Curricular units 1st sem (grade)                4413 non-null   float64
 23  Curricular units 1st sem (without evaluations)  4413 non-null   int64
 24  Curricular units 2nd sem (credited)             4413 non-null   int64
 25  Curricular units 2nd sem (enrolled)             4413 non-null   int64
 26  Curricular units 2nd sem (evaluations)          4413 non-null   int64
 27  Curricular units 2nd sem (approved)             4413 non-null   int64
 28  Curricular units 2nd sem (grade)                4413 non-null   float64
 29  Curricular units 2nd sem (without evaluations)  4413 non-null   int64
 30  Unemployment rate                               4413 non-null   float64
 31  Inflation rate                                  4413 non-null   float64
 32  GDP                                             4413 non-null   float64
 33  Target                                          4413 non-null   str
dtypes: float64(11), int64(22), str(1)
memory usage: 1.2 MB

# Encoding

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
encoder=LabelEncoder()

In [16]:
encoder

LabelEncoder()

In [17]:
df['Target']=encoder.fit_transform(df['Target'])

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 4413 entries, 0 to 4423
Data columns (total 34 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4413 non-null   int64
 1   Application mode                                4413 non-null   int64
 2   Application order                               4413 non-null   int64
 3   Course                                          4413 non-null   int64
 4   Daytime/evening attendance                      4413 non-null   float64
 5   Previous qualification                          4413 non-null   int64
 6   Mother's qualification                          4413 non-null   int64
 7   Father's qualification                          4413 non-null   int64
 8   Mother's occupation                             4413 non-null   int64
 9   Father's occupation                             4413 non-null   int64
 10  Displaced                                       4413 non-null   int64
 11  Educational special needs                       4413 non-null   float64
 12  Debtor                                          4413 non-null   float64
 13  Tuition fees up to date                         4413 non-null   float64
 14  Gender                                          4413 non-null   float64
 15  Scholarship holder                              4413 non-null   float64
 16  Age at enrollment                               4413 non-null   int64
 17  International                                   4413 non-null   int64
 18  Curricular units 1st sem (credited)             4413 non-null   int64
 19  Curricular units 1st sem (enrolled)             4413 non-null   int64
 20  Curricular units 1st sem (evaluations)          4413 non-null   int64
 21  Curricular units 1st sem (approved)             4413 non-null   int64
 22  Curricular units 1st sem (grade)                4413 non-null   float64
 23  Curricular units 1st sem (without evaluations)  4413 non-null   int64
 24  Curricular units 2nd sem (credited)             4413 non-null   int64
 25  Curricular units 2nd sem (enrolled)             4413 non-null   int64
 26  Curricular units 2nd sem (evaluations)          4413 non-null   int64
 27  Curricular units 2nd sem (approved)             4413 non-null   int64
 28  Curricular units 2nd sem (grade)                4413 non-null   float64
 29  Curricular units 2nd sem (without evaluations)  4413 non-null   int64
 30  Unemployment rate                               4413 non-null   float64
 31  Inflation rate                                  4413 non-null   float64
 32  GDP                                             4413 non-null   float64
 33  Target                                          4413 non-null   int64
dtypes: float64(11), int64(23)
memory usage: 1.2 MB

In [19]:
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,8,5,2,1.0,1,13,10,6,10,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,0
1,1,6,1,11,1.0,1,1,3,4,4,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,2
13,1,17,1,11,1.0,16,1,1,5,8,...,0,6,8,5,11.000000,0,8.9,1.4,3.51,2
14,1,1,1,6,1.0,1,23,27,6,6,...,0,5,5,5,12.000000,0,10.8,1.4,1.74,2
15,1,1,1,15,1.0,1,13,27,10,4,...,0,6,7,0,0.000000,0,15.5,2.8,-4.06,0

# Scaling

In [20]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler

# StandardScaler

In [21]:
scaler=MinMaxScaler()

In [22]:
scaler

MinMaxScaler()

In [23]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Target')

In [24]:
num_col

Index(['Marital status', 'Application mode', 'Application order', 'Course',
       'Daytime/evening attendance', 'Previous qualification',
       'Mother's qualification', 'Father's qualification',
       'Mother's occupation', 'Father's occupation', 'Displaced',
       'Educational special needs', 'Debtor', 'Tuition fees up to date',
       'Gender', 'Scholarship holder', 'Age at enrollment', 'International',
       'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (enrolled)',
       'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (approved)',
       'Curricular units 1st sem (grade)',
       'Curricular units 1st sem (without evaluations)',
       'Curricular units 2nd sem (credited)',
       'Curricular units 2nd sem (enrolled)',
       'Curricular units 2nd sem (evaluations)',
       'Curricular units 2nd sem (approved)',
       'Curricular units 2nd sem (grade)',
       'Curricular units 2nd sem (without evaluations)', 'Unemployment rate',
       'Inflation rate', 'GDP'],
      dtype='str')

In [25]:
df[num_col]=scaler.fit_transform(df[num_col])

In [26]:
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,0.0,0.411765,0.555556,0.0625,1.0,0.0000,0.428571,0.272727,0.161290,0.200000,...,0.0,0.000000,0.000000,0.00,0.000000,0.0,0.372093,0.488889,0.766182,0
1,0.0,0.294118,0.111111,0.6250,1.0,0.0000,0.000000,0.060606,0.096774,0.066667,...,0.0,0.260870,0.181818,0.30,0.735897,0.0,0.732558,0.111111,0.640687,2
13,0.0,0.941176,0.111111,0.6250,1.0,0.9375,0.000000,0.000000,0.129032,0.155556,...,0.0,0.260870,0.242424,0.25,0.592308,0.0,0.151163,0.488889,1.000000,2
14,0.0,0.000000,0.111111,0.3125,1.0,0.0000,0.785714,0.787879,0.161290,0.111111,...,0.0,0.217391,0.151515,0.25,0.646154,0.0,0.372093,0.488889,0.766182,2
15,0.0,0.000000,0.111111,0.8750,1.0,0.0000,0.428571,0.787879,0.290323,0.066667,...,0.0,0.260870,0.212121,0.00,0.000000,0.0,0.918605,0.800000,0.000000,0

In [27]:
df.info()

<class 'pandas.DataFrame'>
Index: 4413 entries, 0 to 4423
Data columns (total 34 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4413 non-null   float64
 1   Application mode                                4413 non-null   float64
 2   Application order                               4413 non-null   float64
 3   Course                                          4413 non-null   float64
 4   Daytime/evening attendance                      4413 non-null   float64
 5   Previous qualification                          4413 non-null   float64
 6   Mother's qualification                          4413 non-null   float64
 7   Father's qualification                          4413 non-null   float64
 8   Mother's occupation                             4413 non-null   float64
 9   Father's occupation                             4413 non-null   float64
 10  Displaced                                       4413 non-null   float64
 11  Educational special needs                       4413 non-null   float64
 12  Debtor                                          4413 non-null   float64
 13  Tuition fees up to date                         4413 non-null   float64
 14  Gender                                          4413 non-null   float64
 15  Scholarship holder                              4413 non-null   float64
 16  Age at enrollment                               4413 non-null   float64
 17  International                                   4413 non-null   float64
 18  Curricular units 1st sem (credited)             4413 non-null   float64
 19  Curricular units 1st sem (enrolled)             4413 non-null   float64
 20  Curricular units 1st sem (evaluations)          4413 non-null   float64
 21  Curricular units 1st sem (approved)             4413 non-null   float64
 22  Curricular units 1st sem (grade)                4413 non-null   float64
 23  Curricular units 1st sem (without evaluations)  4413 non-null   float64
 24  Curricular units 2nd sem (credited)             4413 non-null   float64
 25  Curricular units 2nd sem (enrolled)             4413 non-null   float64
 26  Curricular units 2nd sem (evaluations)          4413 non-null   float64
 27  Curricular units 2nd sem (approved)             4413 non-null   float64
 28  Curricular units 2nd sem (grade)                4413 non-null   float64
 29  Curricular units 2nd sem (without evaluations)  4413 non-null   float64
 30  Unemployment rate                               4413 non-null   float64
 31  Inflation rate                                  4413 non-null   float64
 32  GDP                                             4413 non-null   float64
 33  Target                                          4413 non-null   int64
dtypes: float64(33), int64(1)
memory usage: 1.2 MB

x---inputs
y---output

In [28]:
num_col=df.select_dtypes(include=['float64']).columns

In [29]:
num_col

Index(['Marital status', 'Application mode', 'Application order', 'Course',
       'Daytime/evening attendance', 'Previous qualification',
       'Mother's qualification', 'Father's qualification',
       'Mother's occupation', 'Father's occupation', 'Displaced',
       'Educational special needs', 'Debtor', 'Tuition fees up to date',
       'Gender', 'Scholarship holder', 'Age at enrollment', 'International',
       'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (enrolled)',
       'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (approved)',
       'Curricular units 1st sem (grade)',
       'Curricular units 1st sem (without evaluations)',
       'Curricular units 2nd sem (credited)',
       'Curricular units 2nd sem (enrolled)',
       'Curricular units 2nd sem (evaluations)',
       'Curricular units 2nd sem (approved)',
       'Curricular units 2nd sem (grade)',
       'Curricular units 2nd sem (without evaluations)', 'Unemployment rate',
       'Inflation rate', 'GDP'],
      dtype='str')

In [30]:
x=df.drop('Target',axis=1)

In [31]:
x

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
0,0.0,0.411765,0.555556,0.0625,1.0,0.0000,0.428571,0.272727,0.161290,0.200000,...,0.0,0.0,0.000000,0.000000,0.00,0.000000,0.0,0.372093,0.488889,0.766182
1,0.0,0.294118,0.111111,0.6250,1.0,0.0000,0.000000,0.060606,0.096774,0.066667,...,0.0,0.0,0.260870,0.181818,0.30,0.735897,0.0,0.732558,0.111111,0.640687
13,0.0,0.941176,0.111111,0.6250,1.0,0.9375,0.000000,0.000000,0.129032,0.155556,...,0.0,0.0,0.260870,0.242424,0.25,0.592308,0.0,0.151163,0.488889,1.000000
14,0.0,0.000000,0.111111,0.3125,1.0,0.0000,0.785714,0.787879,0.161290,0.111111,...,0.0,0.0,0.217391,0.151515,0.25,0.646154,0.0,0.372093,0.488889,0.766182
15,0.0,0.000000,0.111111,0.8750,1.0,0.0000,0.428571,0.787879,0.290323,0.066667,...,0.0,0.0,0.260870,0.212121,0.00,0.000000,0.0,0.918605,0.800000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,0.0,0.000000,0.666667,0.8750,1.0,0.0000,0.000000,0.000000,0.161290,0.088889,...,0.0,0.0,0.260870,0.242424,0.25,0.682051,0.0,0.918605,0.800000,0.000000
4420,0.0,0.000000,0.222222,0.8750,1.0,0.0000,0.000000,0.000000,0.290323,0.200000,...,0.0,0.0,0.260870,0.181818,0.10,0.592308,0.0,0.406977,0.311111,0.803170
4421,0.0,0.000000,0.111111,0.6875,1.0,0.0000,0.750000,0.787879,0.290323,0.200000,...,0.0,0.0,0.347826,0.272727,0.05,0.726923,0.0,0.732558,0.111111,0.640687
4422,0.0,0.000000,0.111111,0.5000,1.0,0.0000,0.750000,0.787879,0.225806,0.088889,...,0.0,0.0,0.217391,0.181818,0.25,0.646154,0.0,0.209302,0.000000,0.124174
4423,0.0,0.235294,0.111111,0.8750,1.0,0.0000,0.785714,0.787879,0.161290,0.200000,...,0.0,0.0,0.260870,0.181818,0.30,0.700000,0.0,0.593023,1.000000,0.311757

In [32]:
y=df['Target']

In [33]:
y

0       0
1       2
13      2
14      2
15      0
       ..
4419    2
4420    0
4421    0
4422    2
4423    2
Name: Target, Length: 4413, dtype: int64

# Splitting

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [51]:
x_train. shape

(3089, 33)

In [52]:
x_test.shape

(1324, 33)

In [53]:
y_train.shape

(3089,)

In [54]:
y_test.shape

(1324,)

# Logistic regression

In [55]:
from sklearn.linear_model import LogisticRegression

In [56]:
log_reg=LogisticRegression()

In [57]:
log_reg

LogisticRegression()

# training

In [58]:
log_reg.fit(x_train,y_train)

LogisticRegression()

# predicting

In [59]:
y_pred=log_reg.predict(x_test)

In [60]:

y_pred[1:10]

array([2, 0, 2, 2, 2, 0, 2, 2, 0])

# evaluation

In [61]:
from sklearn.metrics import accuracy_score

In [62]:
score=accuracy_score(y_test,y_pred)

In [63]:
print('Modelning aniqlik darajasi:',score)

Modelning aniqlik darajasi: 0.7764350453172205