In [2]:
a=[1,2,3]
for i in a:
    print(i)

1
2
3

In [3]:
for i in a:
    print(i+1)

2
3
4

In [4]:
for i in a:
    print(i*2)

2
4
6

In [5]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9

In [6]:
for i in range(1,10):
    if i%2==0:
        print(i)

2
4
6
8

In [7]:
for i in range(1,13):
    if i%2!=0:
        print(i)

1
3
5
7
9
11

In [8]:
for i in range(1,11,2):
    print(i)

1
3
5
7
9

In [9]:
c=['Hello','Hi','Bye']
for i in c:
    print(i)

Hello
Hi
Bye

In [10]:
for i in c:
    print(len(i))

5
2
3

In [11]:
import pandas as pd
df=pd.read_csv('/Users/sunnatabdurayimov/Downloads/Machine_Learning/CAR DETAILS FROM CAR DEKHOk.csv')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   str
 1   year           4337 non-null   float64
 2   selling_price  4337 non-null   float64
 3   km_driven      4338 non-null   float64
 4   fuel           4338 non-null   str
 5   seller_type    4336 non-null   str
 6   transmission   4336 non-null   str
 7   owner          4329 non-null   str
 8   color          4 non-null      str
dtypes: float64(3), str(6)
memory usage: 305.3 KB

In [13]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,color
0,Maruti 800 AC,2007.0,60000.0,70000.0,Petrol,Individual,Manual,First Owner,Red
1,Maruti Wagon R LXI Minor,2007.0,135000.0,50000.0,Petrol,Individual,Manual,First Owner,Blue
2,Hyundai Verna 1.6 SX,2012.0,600000.0,100000.0,Diesel,Individual,Manual,First Owner,Yellow
3,Datsun RediGO T Option,2017.0,250000.0,46000.0,Petrol,Individual,Manual,First Owner,Red
4,Honda Amaze VX i-DTEC,2014.0,450000.0,NaN,Diesel,Individual,Manual,Second Owner,NaN

In [14]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'color'],
      dtype='str')

In [15]:
df.isnull().sum()

name                0
year                3
selling_price       3
km_driven           2
fuel                2
seller_type         4
transmission        4
owner              11
color            4336
dtype: int64

In [16]:
df.isnull().any()

name             False
year              True
selling_price     True
km_driven         True
fuel              True
seller_type       True
transmission      True
owner             True
color             True
dtype: bool

In [20]:
for col in df.columns:
   if df[col].isnull().any():
       if df[col].dtype=='str':
           df.fillna({col:df[col].mode()[0]},inplace=True)
       else:
   
           df.fillna({col:df[col].mean()},inplace=True)

In [21]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
color            0
dtype: int64

In [ ]:
#Encoding + For loop
from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder=LabelEncoder()

In [ ]:
encoder

LabelEncoder()

In [ ]:
df['name']=encoder.fit_transform(df['name'])

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   int64
 1   year           4340 non-null   float64
 2   selling_price  4340 non-null   float64
 3   km_driven      4340 non-null   float64
 4   fuel           4340 non-null   str
 5   seller_type    4340 non-null   str
 6   transmission   4340 non-null   str
 7   owner          4340 non-null   str
 8   color          4340 non-null   str
dtypes: float64(3), int64(1), str(5)
memory usage: 305.3 KB

In [ ]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,color
0,775,2007.0,60000.0,70000.000000,Petrol,Individual,Manual,First Owner,Red
1,1041,2007.0,135000.0,50000.000000,Petrol,Individual,Manual,First Owner,Blue
2,505,2012.0,600000.0,100000.000000,Diesel,Individual,Manual,First Owner,Yellow
3,118,2017.0,250000.0,46000.000000,Petrol,Individual,Manual,First Owner,Red
4,279,2014.0,450000.0,66197.665745,Diesel,Individual,Manual,Second Owner,Red

In [ ]:
df.nunique()

name             1491
year               28
selling_price     446
km_driven         771
fuel                5
seller_type         3
transmission        2
owner               5
color               3
dtype: int64

In [ ]:
df['color']

0          Red
1         Blue
2       Yellow
3          Red
4          Red
         ...
4335       Red
4336       Red
4337       Red
4338       Red
4339       Red
Name: color, Length: 4340, dtype: str

In [ ]:
dummies=pd.get_dummies(df['color'],prefix='ust',dtype=int)

In [ ]:
dummies

      ust_Blue  ust_Red  ust_Yellow
0            0        1           0
1            1        0           0
2            0        0           1
3            0        1           0
4            0        1           0
...        ...      ...         ...
4335         0        1           0
4336         0        1           0
4337         0        1           0
4338         0        1           0
4339         0        1           0

[4340 rows x 3 columns]

In [ ]:
df=pd.concat([df.drop(columns=['color']),dummies],axis=1)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   int64
 1   year           4340 non-null   float64
 2   selling_price  4340 non-null   float64
 3   km_driven      4340 non-null   float64
 4   fuel           4340 non-null   str
 5   seller_type    4340 non-null   str
 6   transmission   4340 non-null   str
 7   owner          4340 non-null   str
 8   ust_Blue       4340 non-null   int64
 9   ust_Red        4340 non-null   int64
 10  ust_Yellow     4340 non-null   int64
dtypes: float64(3), int64(4), str(4)
memory usage: 373.1 KB

In [ ]:
for col in df.columns:
    if df[col].dtype=='str':
        if df[col].nunique()<=3:
            dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
            df=pd.concat([df.drop(columns=col),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   name                          4340 non-null   int64
 1   year                          4340 non-null   float64
 2   selling_price                 4340 non-null   float64
 3   km_driven                     4340 non-null   float64
 4   fuel                          4340 non-null   int64
 5   owner                         4340 non-null   int64
 6   ust_Blue                      4340 non-null   int64
 7   ust_Red                       4340 non-null   int64
 8   ust_Yellow                    4340 non-null   int64
 9   seller_type_Dealer            4340 non-null   int64
 10  seller_type_Individual        4340 non-null   int64
 11  seller_type_Trustmark Dealer  4340 non-null   int64
 12  transmission_Automatic        4340 non-null   int64
 13  transmission_Manual           4340 non-null   int64
dtypes: float64(3), int64(11)
memory usage: 474.8 KB

In [ ]:
df.head(-5)

,name,year,selling_price,km_driven,fuel,owner,ust_Blue,ust_Red,ust_Yellow,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Automatic,transmission_Manual
0,775,2007.0,60000.0,70000.000000,4,0,0,1,0,0,1,0,0,1
1,1041,2007.0,135000.0,50000.000000,4,0,1,0,0,0,1,0,0,1
2,505,2012.0,600000.0,100000.000000,1,0,0,0,1,0,1,0,0,1
3,118,2017.0,250000.0,46000.000000,4,0,0,1,0,0,1,0,0,1
4,279,2014.0,450000.0,66197.665745,1,2,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4330,1228,2010.0,150000.0,130000.000000,1,2,0,1,0,0,1,0,0,1
4331,160,2015.0,530000.0,175000.000000,1,4,0,1,0,0,1,0,0,1
4332,692,2015.0,750000.0,120000.000000,1,0,0,1,0,0,1,0,0,1
4333,928,2012.0,225000.0,90000.000000,1,2,0,1,0,0,1,0,0,1
4334,1418,2012.0,600000.0,170000.000000,1,0,0,1,0,0,1,0,0,1