# Algorithm

In [1]:
import pandas as pd
df=pd.read_csv('/Users/sunnatabdurayimov/Downloads/student_performance_updated_1000.csv')

# Data bilan tanishuv

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  960 non-null    float64
 1   Name                       966 non-null    str
 2   Gender                     952 non-null    str
 3   AttendanceRate             960 non-null    float64
 4   StudyHoursPerWeek          950 non-null    float64
 5   PreviousGrade              967 non-null    float64
 6   ExtracurricularActivities  957 non-null    float64
 7   ParentalSupport            978 non-null    str
 8   FinalGrade                 960 non-null    float64
 9   Study Hours                976 non-null    float64
 10  Attendance (%)             959 non-null    float64
 11  Online Classes Taken       975 non-null    object
dtypes: float64(8), object(1), str(3)
memory usage: 93.9+ KB

In [3]:
df.head()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True

In [4]:
df.isnull().sum()

StudentID                    40
Name                         34
Gender                       48
AttendanceRate               40
StudyHoursPerWeek            50
PreviousGrade                33
ExtracurricularActivities    43
ParentalSupport              22
FinalGrade                   40
Study Hours                  24
Attendance (%)               41
Online Classes Taken         25
dtype: int64

In [5]:
df.columns

Index(['StudentID', 'Name', 'Gender', 'AttendanceRate', 'StudyHoursPerWeek',
       'PreviousGrade', 'ExtracurricularActivities', 'ParentalSupport',
       'FinalGrade', 'Study Hours', 'Attendance (%)', 'Online Classes Taken'],
      dtype='str')

# Data preprocessing

In [6]:
df.drop(['StudentID','Gender'],axis=1,inplace=True)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Name                       966 non-null    str
 1   AttendanceRate             960 non-null    float64
 2   StudyHoursPerWeek          950 non-null    float64
 3   PreviousGrade              967 non-null    float64
 4   ExtracurricularActivities  957 non-null    float64
 5   ParentalSupport            978 non-null    str
 6   FinalGrade                 960 non-null    float64
 7   Study Hours                976 non-null    float64
 8   Attendance (%)             959 non-null    float64
 9   Online Classes Taken       975 non-null    object
dtypes: float64(7), object(1), str(2)
memory usage: 78.3+ KB

In [8]:
df.dropna(inplace=True)

In [9]:
df.info()

<class 'pandas.DataFrame'>
Index: 710 entries, 0 to 998
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Name                       710 non-null    str
 1   AttendanceRate             710 non-null    float64
 2   StudyHoursPerWeek          710 non-null    float64
 3   PreviousGrade              710 non-null    float64
 4   ExtracurricularActivities  710 non-null    float64
 5   ParentalSupport            710 non-null    str
 6   FinalGrade                 710 non-null    float64
 7   Study Hours                710 non-null    float64
 8   Attendance (%)             710 non-null    float64
 9   Online Classes Taken       710 non-null    object
dtypes: float64(7), object(1), str(2)
memory usage: 61.0+ KB

In [10]:
df.head()

,Name,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,John,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,Sarah,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,Alex,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,Michael,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
6,Daniel,70.0,8.0,60.0,0.0,Low,62.0,4.5,96.0,False

# encoding

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
encoder=LabelEncoder()

In [13]:
encoder

LabelEncoder()

In [14]:
for col in df.columns:
    if df[col].dtype=='str':
        df[col]=encoder.fit_transform(df[col])

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 710 entries, 0 to 998
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Name                       710 non-null    int64
 1   AttendanceRate             710 non-null    float64
 2   StudyHoursPerWeek          710 non-null    float64
 3   PreviousGrade              710 non-null    float64
 4   ExtracurricularActivities  710 non-null    float64
 5   ParentalSupport            710 non-null    int64
 6   FinalGrade                 710 non-null    float64
 7   Study Hours                710 non-null    float64
 8   Attendance (%)             710 non-null    float64
 9   Online Classes Taken       710 non-null    object
dtypes: float64(7), int64(2), object(1)
memory usage: 61.0+ KB

In [16]:
df.head()

,Name,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,303,85.0,15.0,78.0,1.0,0,80.0,4.8,59.0,False
1,611,90.0,20.0,85.0,2.0,2,87.0,2.2,70.0,True
2,9,78.0,10.0,65.0,0.0,1,68.0,4.6,92.0,False
3,467,92.0,25.0,90.0,3.0,0,92.0,2.9,96.0,False
6,156,70.0,8.0,60.0,0.0,1,62.0,4.5,96.0,False

# Scaling

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler=MinMaxScaler()
scaler

MinMaxScaler()

In [19]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('FinalGrade')

In [20]:
num_col

Index(['Name', 'AttendanceRate', 'StudyHoursPerWeek', 'PreviousGrade',
       'ExtracurricularActivities', 'ParentalSupport', 'Study Hours',
       'Attendance (%)'],
      dtype='str')

In [21]:
for col in num_col:
    df[num_col]=scaler.fit_transform(df[num_col])

In [22]:
df.head()

,Name,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,0.429178,0.60,0.318182,0.600000,0.333333,0.0,80.0,0.98,0.060000,False
1,0.865439,0.80,0.545455,0.833333,0.666667,1.0,87.0,0.72,0.133333,True
2,0.012748,0.32,0.090909,0.166667,0.000000,0.5,68.0,0.96,0.280000,False
3,0.661473,0.88,0.772727,1.000000,1.000000,0.0,92.0,0.79,0.306667,False
6,0.220963,0.00,0.000000,0.000000,0.000000,0.5,62.0,0.95,0.306667,False

# Algorithm

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
lr=LinearRegression()

In [25]:
lr

LinearRegression()

Training

In [26]:
#x--inputs
#y--output
x=df.drop('FinalGrade',axis=1)

In [27]:
x

,Name,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,Study Hours,Attendance (%),Online Classes Taken
0,0.429178,0.60,0.318182,0.600000,0.333333,0.0,0.98,0.060000,False
1,0.865439,0.80,0.545455,0.833333,0.666667,1.0,0.72,0.133333,True
2,0.012748,0.32,0.090909,0.166667,0.000000,0.5,0.96,0.280000,False
3,0.661473,0.88,0.772727,1.000000,1.000000,0.0,0.79,0.306667,False
6,0.220963,0.00,0.000000,0.000000,0.000000,0.5,0.95,0.306667,False
...,...,...,...,...,...,...,...,...,...
991,0.076487,0.60,1.000000,0.333333,1.000000,1.0,0.54,0.173333,False
992,0.366856,0.84,0.318182,1.000000,0.666667,0.0,0.93,0.120000,False
993,0.716714,0.80,0.772727,0.000000,0.333333,0.5,0.67,0.193333,False
994,0.888102,0.32,0.545455,0.000000,0.000000,0.0,0.66,0.133333,False
998,0.463173,0.72,0.409091,0.000000,0.666667,0.0,0.59,0.020000,True

In [28]:
y=df['FinalGrade']

In [29]:
y

0      80.0
1      87.0
2      68.0
3      92.0
6      62.0
       ...
991    90.0
992    68.0
993    87.0
994    62.0
998    85.0
Name: FinalGrade, Length: 710, dtype: float64

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [32]:
x_train.shape

(568, 9)

In [33]:
x_test.shape

(142, 9)

In [34]:
y_train.shape

(568,)

In [35]:
y_test.shape

(142,)

In [36]:
lr.fit(x_train,y_train)

LinearRegression()

# predicting

In [37]:
y_pred=lr.predict(x_test)

In [38]:
y_pred[4]

np.float64(80.12627419046589)

# evaluation

In [39]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [40]:
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [41]:
print('mae:',mae)
print('mse:',mse)
print('r2:',r2)

mae: 8.207932208082825
mse: 94.37776580093856
r2: -0.03934718865603504