# Scaling

In [23]:
import pandas as pd
df=pd.read_csv('/Users/sunnatabdurayimov/Downloads/adm_datas.csv')

In [11]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337.0,118,4.0,4.5,4.5,9.65,1.0,0.92
1,2,324.0,107,NaN,4.0,4.5,8.87,NaN,0.76
2,3,316.0,104,NaN,3.0,3.5,8.00,NaN,0.72
3,4,322.0,110,NaN,3.5,2.5,8.67,1.0,0.80
4,5,314.0,103,NaN,2.0,3.0,8.21,0.0,0.65

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         400 non-null    int64
 1   GRE Score          394 non-null    float64
 2   TOEFL Score        400 non-null    int64
 3   University Rating  396 non-null    float64
 4   SOP                400 non-null    float64
 5   LOR                398 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           398 non-null    float64
 8   Chance of Admit    400 non-null    float64
dtypes: float64(7), int64(2)
memory usage: 28.3 KB

In [22]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='str')

In [24]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object':
            df[col]=df[col].fillna(df[col].mode()[0],inplace=True)
        else:
            df[col]=df[col].fillna(df[col].mean(),inplace=True)

/var/folders/gj/51m09vr94mn4rflykkzl_yfm0000gn/T/ipykernel_1109/655673500.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col]=df[col].fillna(df[col].mean(),inplace=True)

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         400 non-null    int64
 1   GRE Score          400 non-null    float64
 2   TOEFL Score        400 non-null    int64
 3   University Rating  400 non-null    float64
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    float64
 8   Chance of Admit    400 non-null    float64
dtypes: float64(7), int64(2)
memory usage: 28.3 KB

In [26]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

# Encoding

In [ ]:
# object qiymatlar mavjud bo'lmaganligi uchun bu bosqichni tashlab ketamiz.

In [27]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [ ]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Chance of Admit ')
#Target qiymat scaling qilinmaydi

In [33]:
num_col

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research'],
      dtype='str')

In [35]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337.0,118,4.000000,4.5,4.5,9.65,1.000000,0.92
1,2,324.0,107,3.088384,4.0,4.5,8.87,0.545226,0.76
2,3,316.0,104,3.088384,3.0,3.5,8.00,0.545226,0.72
3,4,322.0,110,3.088384,3.5,2.5,8.67,1.000000,0.80
4,5,314.0,103,3.088384,2.0,3.0,8.21,0.000000,0.65

# StandartScaler

In [36]:
scaler=StandardScaler()

In [38]:
scaler

StandardScaler()

In [39]:
df['GRE Score']=scaler.fit_transform(df[['GRE Score']])

In [40]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,1.775510,118,4.000000,4.5,4.5,9.65,1.000000,0.92
1,2,0.634174,107,3.088384,4.0,4.5,8.87,0.545226,0.76
2,3,-0.068186,104,3.088384,3.0,3.5,8.00,0.545226,0.72
3,4,0.458584,110,3.088384,3.5,2.5,8.67,1.000000,0.80
4,5,-0.243776,103,3.088384,2.0,3.0,8.21,0.000000,0.65

# MinMaxScaler

In [41]:
scaler=MinMaxScaler()

In [42]:
scaler

MinMaxScaler()

In [43]:
df['TOEFL Score']=scaler.fit_transform(df[['TOEFL Score']])

In [44]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,1.775510,0.928571,4.000000,4.5,4.5,9.65,1.000000,0.92
1,2,0.634174,0.535714,3.088384,4.0,4.5,8.87,0.545226,0.76
2,3,-0.068186,0.428571,3.088384,3.0,3.5,8.00,0.545226,0.72
3,4,0.458584,0.642857,3.088384,3.5,2.5,8.67,1.000000,0.80
4,5,-0.243776,0.392857,3.088384,2.0,3.0,8.21,0.000000,0.65

# RobustScaler

In [45]:
scaler=RobustScaler()

In [46]:
scaler

RobustScaler()

In [47]:
df['SOP']=scaler.fit_transform(df[['SOP']])

In [48]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,1.775510,0.928571,4.000000,0.666667,4.5,9.65,1.000000,0.92
1,2,0.634174,0.535714,3.088384,0.333333,4.5,8.87,0.545226,0.76
2,3,-0.068186,0.428571,3.088384,-0.333333,3.5,8.00,0.545226,0.72
3,4,0.458584,0.642857,3.088384,0.000000,2.5,8.67,1.000000,0.80
4,5,-0.243776,0.392857,3.088384,-1.000000,3.0,8.21,0.000000,0.65

# For Loop + Scaling

In [54]:
scaler=MinMaxScaler()
for col in df.columns:
    if df[col].dtype!='str':
        df[col]=scaler.fit_transform(df[[col]])

In [55]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,0.000000,0.94,0.928571,0.750000,0.875,0.875,0.913462,1.000000,0.920635
1,0.002506,0.68,0.535714,0.522096,0.750,0.875,0.663462,0.545226,0.666667
2,0.005013,0.52,0.428571,0.522096,0.500,0.625,0.384615,0.545226,0.603175
3,0.007519,0.64,0.642857,0.522096,0.625,0.375,0.599359,1.000000,0.730159
4,0.010025,0.48,0.392857,0.522096,0.250,0.500,0.451923,0.000000,0.492063

In [60]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Chance of Admit ')
for col in num_col:
    df[col]=scaler.fit_transform(df[[col]])

In [61]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,0.000000,0.94,0.928571,0.750000,0.875,0.875,0.913462,1.000000,0.920635
1,0.002506,0.68,0.535714,0.522096,0.750,0.875,0.663462,0.545226,0.666667
2,0.005013,0.52,0.428571,0.522096,0.500,0.625,0.384615,0.545226,0.603175
3,0.007519,0.64,0.642857,0.522096,0.625,0.375,0.599359,1.000000,0.730159
4,0.010025,0.48,0.392857,0.522096,0.250,0.500,0.451923,0.000000,0.492063