# Model review

In [40]:
import pandas as pd

In [41]:
df=pd.read_csv('/Users/sunnatabdurayimov/Downloads/islamic_Pilgrimage.csv')

# Data bilan tanishuv

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4455 entries, 0 to 4454
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Year                     4455 non-null   int64
 1   Country                  4455 non-null   str
 2   Pilgrimage_Type          4455 non-null   str
 3   Total_Pilgrims           4455 non-null   int64
 4   Male_Percentage          4455 non-null   float64
 5   Female_Percentage        4455 non-null   float64
 6   Average_Age              4453 non-null   float64
 7   Average_Travel_Cost_USD  4455 non-null   float64
 8   Visa_Approval_Rate       4453 non-null   float64
 9   Flights_Arranged         4452 non-null   float64
 10  Hotels_Booked            4453 non-null   float64
 11  Satisfaction_Rating      4455 non-null   float64
 12  Economic_Impact_USD      4455 non-null   float64
dtypes: float64(9), int64(2), str(2)
memory usage: 452.6 KB

In [43]:
df.head()

,Year,Country,Pilgrimage_Type,Total_Pilgrims,Male_Percentage,Female_Percentage,Average_Age,Average_Travel_Cost_USD,Visa_Approval_Rate,Flights_Arranged,Hotels_Booked,Satisfaction_Rating,Economic_Impact_USD
0,2000,Pakistan,Hajj,126958,60.93,39.07,33.5,9686.76,87.31,141.0,224.0,3.12,1.680139e+09
1,2000,Pakistan,Umrah,180203,47.86,52.14,47.5,2092.32,90.94,433.0,201.0,4.98,4.213378e+08
2,2000,Pakistan,Ziyarat,352449,55.50,44.50,41.0,4557.91,87.74,189.0,197.0,3.73,1.535860e+09
3,2000,Saudi Arabia,Hajj,89654,57.37,42.63,39.5,11823.92,83.54,326.0,144.0,3.34,5.989896e+08
4,2000,Saudi Arabia,Umrah,146699,63.84,36.16,44.9,5546.87,70.46,405.0,101.0,3.88,5.061651e+08

In [44]:
df.isnull().sum()

Year                       0
Country                    0
Pilgrimage_Type            0
Total_Pilgrims             0
Male_Percentage            0
Female_Percentage          0
Average_Age                2
Average_Travel_Cost_USD    0
Visa_Approval_Rate         2
Flights_Arranged           3
Hotels_Booked              2
Satisfaction_Rating        0
Economic_Impact_USD        0
dtype: int64

# Data preprocessing

In [45]:
df.columns

Index(['Year', 'Country', 'Pilgrimage_Type', 'Total_Pilgrims',
       'Male_Percentage', 'Female_Percentage', 'Average_Age',
       'Average_Travel_Cost_USD', 'Visa_Approval_Rate', 'Flights_Arranged',
       'Hotels_Booked', 'Satisfaction_Rating', 'Economic_Impact_USD'],
      dtype='str')

In [46]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='float64':
            df.fillna({col:df[col].mean()},inplace=True)

In [47]:
df.isnull().sum()

Year                       0
Country                    0
Pilgrimage_Type            0
Total_Pilgrims             0
Male_Percentage            0
Female_Percentage          0
Average_Age                0
Average_Travel_Cost_USD    0
Visa_Approval_Rate         0
Flights_Arranged           0
Hotels_Booked              0
Satisfaction_Rating        0
Economic_Impact_USD        0
dtype: int64

In [48]:
df.head()

,Year,Country,Pilgrimage_Type,Total_Pilgrims,Male_Percentage,Female_Percentage,Average_Age,Average_Travel_Cost_USD,Visa_Approval_Rate,Flights_Arranged,Hotels_Booked,Satisfaction_Rating,Economic_Impact_USD
0,2000,Pakistan,Hajj,126958,60.93,39.07,33.5,9686.76,87.31,141.0,224.0,3.12,1.680139e+09
1,2000,Pakistan,Umrah,180203,47.86,52.14,47.5,2092.32,90.94,433.0,201.0,4.98,4.213378e+08
2,2000,Pakistan,Ziyarat,352449,55.50,44.50,41.0,4557.91,87.74,189.0,197.0,3.73,1.535860e+09
3,2000,Saudi Arabia,Hajj,89654,57.37,42.63,39.5,11823.92,83.54,326.0,144.0,3.34,5.989896e+08
4,2000,Saudi Arabia,Umrah,146699,63.84,36.16,44.9,5546.87,70.46,405.0,101.0,3.88,5.061651e+08

# Encoding

In [49]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [50]:
encoder=LabelEncoder()

In [51]:
encoder

LabelEncoder()

In [52]:
df.nunique()

Year                         27
Country                      55
Pilgrimage_Type               3
Total_Pilgrims             4436
Male_Percentage            1767
Female_Percentage          1767
Average_Age                 302
Average_Travel_Cost_USD    4446
Visa_Approval_Rate         2290
Flights_Arranged            481
Hotels_Booked               291
Satisfaction_Rating         201
Economic_Impact_USD        4455
dtype: int64

In [53]:
for col in df.columns:
    if df[col].dtype=='str':
        df[col]=encoder.fit_transform(df[col])

In [54]:
df.head()

,Year,Country,Pilgrimage_Type,Total_Pilgrims,Male_Percentage,Female_Percentage,Average_Age,Average_Travel_Cost_USD,Visa_Approval_Rate,Flights_Arranged,Hotels_Booked,Satisfaction_Rating,Economic_Impact_USD
0,2000,33,0,126958,60.93,39.07,33.5,9686.76,87.31,141.0,224.0,3.12,1.680139e+09
1,2000,33,1,180203,47.86,52.14,47.5,2092.32,90.94,433.0,201.0,4.98,4.213378e+08
2,2000,33,2,352449,55.50,44.50,41.0,4557.91,87.74,189.0,197.0,3.73,1.535860e+09
3,2000,37,0,89654,57.37,42.63,39.5,11823.92,83.54,326.0,144.0,3.34,5.989896e+08
4,2000,37,1,146699,63.84,36.16,44.9,5546.87,70.46,405.0,101.0,3.88,5.061651e+08

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4455 entries, 0 to 4454
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Year                     4455 non-null   int64
 1   Country                  4455 non-null   int64
 2   Pilgrimage_Type          4455 non-null   int64
 3   Total_Pilgrims           4455 non-null   int64
 4   Male_Percentage          4455 non-null   float64
 5   Female_Percentage        4455 non-null   float64
 6   Average_Age              4455 non-null   float64
 7   Average_Travel_Cost_USD  4455 non-null   float64
 8   Visa_Approval_Rate       4455 non-null   float64
 9   Flights_Arranged         4455 non-null   float64
 10  Hotels_Booked            4455 non-null   float64
 11  Satisfaction_Rating      4455 non-null   float64
 12  Economic_Impact_USD      4455 non-null   float64
dtypes: float64(9), int64(4)
memory usage: 452.6 KB

# Scaling

In [56]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler

MinMaxScaler()

In [57]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Average_Travel_Cost_USD')

In [58]:
num_col

Index(['Year', 'Country', 'Pilgrimage_Type', 'Total_Pilgrims',
       'Male_Percentage', 'Female_Percentage', 'Average_Age',
       'Visa_Approval_Rate', 'Flights_Arranged', 'Hotels_Booked',
       'Satisfaction_Rating', 'Economic_Impact_USD'],
      dtype='str')

In [59]:
df[num_col]=scaler.fit_transform(df[num_col])

In [60]:
df.head()

,Year,Country,Pilgrimage_Type,Total_Pilgrims,Male_Percentage,Female_Percentage,Average_Age,Average_Travel_Cost_USD,Visa_Approval_Rate,Flights_Arranged,Hotels_Booked,Satisfaction_Rating,Economic_Impact_USD
0,0.0,0.611111,0.0,0.246410,0.7965,0.2035,0.183333,9686.76,0.596897,0.252610,0.740484,0.060,0.200857
1,0.0,0.611111,0.5,0.353993,0.1430,0.8570,0.650000,2092.32,0.722069,0.862213,0.660900,0.990,0.049856
2,0.0,0.611111,1.0,0.702021,0.5250,0.4750,0.433333,4557.91,0.611724,0.352818,0.647059,0.365,0.183550
3,0.0,0.685185,0.0,0.171036,0.6185,0.3815,0.383333,11823.92,0.466897,0.638831,0.463668,0.170,0.071166
4,0.0,0.685185,0.5,0.286297,0.9420,0.0580,0.563333,5546.87,0.015862,0.803758,0.314879,0.440,0.060031

# Algorithm selection

In [61]:
from sklearn.linear_model import LinearRegression
lir=LinearRegression()
lir

LinearRegression()

In [62]:
#x--inputs
x=df.drop('Average_Travel_Cost_USD',axis=1)

In [63]:
x

,Year,Country,Pilgrimage_Type,Total_Pilgrims,Male_Percentage,Female_Percentage,Average_Age,Visa_Approval_Rate,Flights_Arranged,Hotels_Booked,Satisfaction_Rating,Economic_Impact_USD
0,0.0,0.611111,0.0,0.246410,0.7965,0.2035,0.183333,0.596897,0.252610,0.740484,0.060,0.200857
1,0.0,0.611111,0.5,0.353993,0.1430,0.8570,0.650000,0.722069,0.862213,0.660900,0.990,0.049856
2,0.0,0.611111,1.0,0.702021,0.5250,0.4750,0.433333,0.611724,0.352818,0.647059,0.365,0.183550
3,0.0,0.685185,0.0,0.171036,0.6185,0.3815,0.383333,0.466897,0.638831,0.463668,0.170,0.071166
4,0.0,0.685185,0.5,0.286297,0.9420,0.0580,0.563333,0.015862,0.803758,0.314879,0.440,0.060031
...,...,...,...,...,...,...,...,...,...,...,...,...
4450,1.0,0.851852,0.5,0.044320,0.8505,0.1495,0.133333,0.947241,0.187891,0.647059,0.115,0.019668
4451,1.0,0.851852,1.0,0.150162,0.0455,0.9545,0.710000,0.701034,0.661795,0.086505,0.250,0.097561
4452,1.0,0.055556,0.0,0.938774,0.8935,0.1065,0.650000,0.621724,0.605428,0.103806,0.535,0.504930
4453,1.0,0.055556,0.5,0.447919,0.4810,0.5190,0.996667,0.854138,0.300626,0.429066,0.010,0.079251
4454,1.0,0.055556,1.0,0.804554,0.4260,0.5740,0.003333,0.619310,0.106472,0.128028,0.945,0.460617

In [64]:
# y---output
y=df['Average_Travel_Cost_USD']

In [65]:
y

0        9686.76
1        2092.32
2        4557.91
3       11823.92
4        5546.87
          ...
4450     6282.84
4451    10381.19
4452     9258.00
4453     5531.26
4454     6739.69
Name: Average_Travel_Cost_USD, Length: 4455, dtype: float64

# train

In [66]:
from sklearn.model_selection import train_test_split

In [67]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [68]:
x_train.shape

(3564, 12)

In [69]:
x_test.shape

(891, 12)

In [70]:
y_train.shape

(3564,)

In [71]:
y_test.shape

(891,)

In [72]:
lir.fit(x_train,y_train)

LinearRegression()

# Prediction

In [73]:
y_pred=lir.predict(x_test)

In [75]:
y_pred[0]

np.float64(8958.020434959833)

# Evaluation

In [76]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [77]:
mae=mean_absolute_error(y_test,y_pred)
mse= mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [81]:
print('mae=',mae)
print('mse=',mse)
print('r2=',r2)

mae= 1801.5269798523611
mse= 4843864.168185441
r2= 0.4932647036716652